### ISSUE TITLE
Hand model for the different hands a player can use in a given round in the rules engine

### ISSUE THREAD

**Issue by ppeters0502** [CYBR8470/Semester-Project#28]
This will be part of the rules engine and will be the base for how points will accumulate and what hands are available for a player to select.
The different hands that can be selected in this game are:
- Ones
- Twos
- Threes
- Fours
- Fives
- Sixes
- Three of a kind
- Four of a kind
- Full House
- Small Straight
- Large Straight
- YAHTZEE
- Chance
There are three different ways that the hands are scored, either a complete sum (all of the dice values are added together, such as in Chance, or three/four of a kind), a partial sum (all of the threes are added together, or all of the twos are added together, for example), or a static value (Full House scores 25 points, Large Straight scores 40 points, etc). Based off of that type of scoring and the different hands, here's kind of what I'm thinking for a start to this model:

| Property      | Type    | Description                                                     | 
|---------------|---------|-----------------------------------------------------------------|
| Hand_ID       | integer | unique identifier to the hand                                   |
| Hand_Name     | string  | name of the hand that will be displayed in the score sheet      |
| Score_Type_Id | integer | 1 for Complete Sum, 2 for Partial Sum, 3 for Static Points      |
| Points        | integer | When Score_Type_Id is Static Points, these are the points added |

**Comment by abullockuno** [comment]
I'd call this the score model. 
- Game_ID - foreign key
- Player_ID - foreign key
- Ones (int)
- Twos (int)
- Threes (...)
- Fours
- Fives
- Sixes
- Three of a kind
- ...
- Yahtzee
- Yahtzee_Count
- Chance

scoring and possible score for each field will be generated and displayed per round. When entry is selected for a round backend inputs backend calculated score into that field.

**Comment by abullockuno** [comment]
we need another "hand" model which in this case will be five dice, all 1-6 ints. (and maybe 5 more fields for sorting logic)
Say player has:
1 6 5 2 4 1
first, sort die
1 1 2 4 5 6
then logic goes 
sum_ones(count 1's)
sum_twos(count 2's x 2)
...
3_oak( does 2nd match first? yes - does 3rd match 2nd? yes - val 3rd *3 + 4th +5th
                                                                                          no - does 4th match 3rd? yes does 5th match 3rd? 
                                                                                                                                   no - 1st + 2nd + 3rd + 4th + 5th
                                              no - does 3rd match 2nd? ..
4_oak is similar
small straight similar but +1 instead of = using 4_oak logic
large straight checks all 5
yahtzee is just 5_oak
chance is always 1+2+3+4+5

when a field is null (or is 0???) that value can be calculated and allows a score to enter into that field in the score model. once that field is is not null, there is no longer a calculation or the ability to enter a score into that field in the score model.

**Comment by abullockuno** [comment]
Yahtzee has a special rule that I'll have to look up again, but again just controlled by logic on the backend concerning which fields can input which scores

**Comment by abullockuno** [comment]
We'll have to have the score fields start as null, and a zero value counts as an entered value, as some scores will be 0. There are also some bonuses that will need logic built out for the final score, but that won't be too hard.

**Comment by ppeters0502** [comment]
The score model I totally agree with, that makes sense!
The "other" hand model with the dice we'll have to talk through, I think I'm following what you're saying, but I'll understand it a bit better as we talk through it.

**Comment by abullockuno** [comment]
the hand model will need an additional field for bonus values

**Comment by abullockuno** [comment]
#33
