### ISSUE TITLE
heartbeat request on game page

### ISSUE THREAD

**Issue by ppeters0502** [CYBR8470/Semester-Project#39]
Since we're not using websockets/django-channels, the player's screen is only going to be updated when requests are sent out by the client and returned by the server. To keep the player connected to what's going on in the game then, we'll need a request that will be sent automatically every few seconds that can get the information that'll be needed to update in realtime(ish). Stuff like players score, who's still rolling dice, etc.
We'll want to keep this a fairly simple request that doesn't get bogged down with too much data, since it'll be firing off for each player in each game every couple of seconds.

**Comment by abullockuno** [comment]
<meta http-equiv="refresh" content="30"> in the head tag of the page will refresh the every thirty seconds

**Comment by abullockuno** [comment]
"<meta http-equiv="refresh" content="30">"

**Comment by abullockuno** [comment]
FFS &LTmeta http-equiv="refresh" content="30"&GT

**Comment by abullockuno** [comment]
but do < and > for the actual html

**Comment by abullockuno** [comment]
location.reload() also refreshes the page manually, on a button click, say
